
on: [workflow_dispatch]
name: ACI_Deploy

permissions:
      id-token: write
      contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
      #CLI Dependency Testing - START

        - name: Installing CLI-beta for OIDC
          run: |
               CWD="$(pwd)"  
               python3 -m venv oidc-venv
               . oidc-venv/bin/activate
               echo "activated environment" 
               python3 -m pip install -q --upgrade pip
               echo "started installing cli beta" 
               pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
               echo "***************installed cli beta*******************" 
               echo "$CWD/oidc-venv/bin" >> $GITHUB_PATH
               
       #CLI Dependency Testing - END

          
        - name: 'Az CLI login'
          uses: 'azure/login@oidc-support'
          with:
                  client-id: ${{ secrets.AZURE_CLIENTID }}
                  tenant-id: ${{ secrets.AZURE_TENANTID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}        

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: TestResourceGroup
            dns-name-label: "ajaykalecontainer"
            image: nginx
            #registry-username: ${{ secrets.REGISTRY_USERNAME }}
            #registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: contoso-container
            location: 'west us'
