name: Run Azure deployment with OIDC login
on: workflow_dispatch

permissions:
      id-token: write
      contents: write
env:
  AZURE_WEBAPP_NAME: gayatri-webapp-py # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '~/pythonSample_thecatsaidno'         # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.7'                  # set this to the python version to use
jobs: 
  az-deployment-test:
    runs-on: self-hosted
    steps:
      - name: Check out current repo 
        uses: actions/checkout@v2
      - name: Check out app's repo
        uses: actions/checkout@v2
        with:
          repository: Azure-Samples/pythonSample_thecatsaidno
          ref: master
          path: 'pythonSample_thecatsaidno'
      - run: |
            echo $PATH
      - name: Installing CLI-beta for OIDC and apps dependencies 
        run: |
           pwd 
           python3 -m venv oidc-venv
           ls
           . oidc-venv/bin/activate
           python3 -m pip install --upgrade pip
           pip install --extra-index-url https://azurecliedge.blob.core.windows.net/federated-token/simple/ azure-cli
           pip install -r pythonSample_thecatsaidno/requirements.txt
           
      - name: 'Az CLI login without subscription'
        uses: 'balaga-gayatri/login@oidc-support'
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_OIDC }}
#           allow-no-subscriptions: true
#           enable-AzPSSession: true
          
      - name: 'Run az commands'
        run: |
          pwd
          which az
          . oidc-venv/bin/activate
          az account show
          az group list
          pwd
          cd
          cat .zshrc
          
          
      - name: 'Deploy using webapps-deploy'
        uses: Azure/webapps-deploy@v2
        with: 
           app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
           package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

