name: Run Azure deployment with OIDC login
on: workflow_dispatch

permissions:
      id-token: write
      contents: write
env:
  AZURE_WEBAPP_NAME: gayatri-webapp-py # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'pythonSample_thecatsaidno'         # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.7'                  # set this to the python version to use
jobs: 
  az-deployment-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repo 
        uses: actions/checkout@v2
      - name: Check out app's repo
        uses: actions/checkout@v2
        with:
          repository: Azure-Samples/pythonSample_thecatsaidno
          ref: master
          path: 'pythonSample_thecatsaidno'
     
      - name: 'Az CLI OIDC login with subscription'
        uses: 'azure/login@v1'
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}
#           creds: ${{ secrets.AZURE_CREDENTIALS_OIDC }}
#           allow-no-subscriptions: true
#           enable-AzPSSession: true
    
      - name: 'Deploy using webapps-deploy'
        uses: Azure/webapps-deploy@v2
        with: 
           app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
           package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
