name: Run Azure Login for OIDC
on: workflow_dispatch

permissions:
      id-token: write
      contents: write
jobs: 
  az-login-test:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Installing CLI-beta for OIDC
        run: |
           CWD="$(pwd)"   
           echo "/Users/balaga-gayatri/oidc-venv/bin" >> $GITHUB_PATH
      - name: 'Az CLI login with subscription'
        uses: 'balaga-gayatri/login@oidc-support'
        with:
#           client-id: ${{ secrets.AZURE_CLIENTID }}
#           tenant-id: ${{ secrets.AZURE_TENANTID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
#           enable-AzPSSession: true
#          environment: azurestack
          
      - run: |
          pwd
          az account show
          az group list
          pwd 
    
#    python3 -m venv oidc-venv
#            . oidc-venv/bin/activate
#            echo "***********activated environment**********" 
#            python3 -m pip install --upgrade pip
#            echo "***************started installing cli beta*******************" 
#            pip install -q --extra-index-url https://azurecliedge.blob.core.windows.net/federated-token/simple/ azure-cli
#            echo "***************installed cli beta*******************" 
#            echo "$CWD/oidc-venv/bin" >> $GITHUB_PATH
           
