name: Run Azure Login with OIDC(testing)
on: [workflow_dispatch, pull_request]
# D:\a\azure-login-action-tests\azure-login-action-tests\
#            py -3.10 -m venv oidc-venv

permissions:
      id-token: write
      contents: read
jobs: 
  az-login-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: testing files-1
        run: |
          which az
          echo $PATH
#  master-logs-working         
      - name: 'Az CLI login'
        uses: 'azure/login@v1.4.0'
        with:
          client-id: ba719d67-d880-40b0-926f-b21ed26856b0 #8751f16d-d2bc-49ea-8c19-1fd2b19b22bf #8751f16d-d2bc-49ea-8c19-1fd2b19b22bf #${{ secrets.AZURE_CLIENTID }}
          tenant-id: 72f988bf-86f1-41af-91ab-2d7cd011db47 #${{ secrets.AZURE_TENANTID }}
          subscription-id: c00d16c7-6c1f-4c03-9be1-6934a4c49682 #${{ secrets.AZURE_SUBSCRIPTIONID }}     
#           audience: 'api:ADToken'
#           creds: ${{ secrets.AZURE_CREDENTIALS }}
          #allow-no-subscriptions: true
          enable-AzPSSession: true
          #environment: azurestack
          
      - name: Check out repository
        uses: actions/checkout@v2
  
      - name: testing files-2
        run: |
            which az
            ls
              
      - run: |
          az account show
          az group list
          pwd 
    
      # windows CLI installation     
#       - run: |
#             cd ../..
#             $CWD = Convert-Path .
#             echo $CWD
#             python --version
#             python -m venv oidc-venv
#             . .\oidc-venv\Scripts\Activate.ps1
#             python -m pip install -q --upgrade pip
#             echo "started installing cli beta" 
#             pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
#             echo "***************installed cli beta*******************" 
#             echo "$CWD\oidc-venv\Scripts" >> $env:GITHUB_PATH
#       ubuntu/macos installation
#       - name: Installing CLI-beta for OIDC and apps dependencies 
#         run: |
#            cd ../..
#            CWD="$(pwd)"
#            python3 -m venv oidc-venv
#            . oidc-venv/bin/activate
#            echo "***********activated environment**********" 
#            python3 -m pip install --upgrade pip
#            echo "***************started installing cli beta*******************" 
#            pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
#            echo "***************installed cli beta*******************"    
#            echo "$CWD/oidc-venv/bin" >> $GITHUB_PATH   
      # common 
#       - name: Installing preview Az.accounts for powershell
#         shell: pwsh
#         run: |
#           cd ../../oidc-venv
#           Invoke-WebRequest -Uri https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.6.0.nupkg -outfile "Az.Accounts.2.6.0.nupkg"
#           Register-PSRepository -Name LocalPSRepo -SourceLocation "$(pwd)" -ScriptSourceLocation "$(pwd)" -InstallationPolicy Trusted
#           Install-Module Az.Accounts -Repository LocalPSRepo
