name: Run Azure Login for OIDC
on: workflow_dispatch


jobs: 
  az-login-test:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Installing CLI-beta for OIDC
        run: |
           python -m venv oidc-venv
           .oidc-venv/bin/activate
           python -m pip install --upgrade pip
           pip install --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
           

      - name: 'Az CLI login with subscription'
        uses: 'balaga-gayatri/login@oidc-support'
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_OIDC }}
#           enable-AzPSSession: true
          
      - run: |
          az account show
          pwd 
      - name: deactive and remove cli beta venv
        run: |
          deactivate
          rm -rf oidc-venv
