name: Run Azure deployment with OIDC login
on: workflow_dispatch

permissions:
      id-token: write
      contents: write
env:
  AZURE_WEBAPP_NAME: gayatri-webapp-py # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'pythonSample_thecatsaidno'         # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.7'                  # set this to the python version to use
jobs: 
  az-deployment-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repo 
        uses: actions/checkout@v2
      - name: Check out app's repo
        uses: actions/checkout@v2
        with:
          repository: Azure-Samples/pythonSample_thecatsaidno
          ref: master
          path: 'pythonSample_thecatsaidno'
      - run: |
            echo $PATH
      - name: Installing CLI-beta for OIDC and apps dependencies 
        run: |
           pwd 
           python3 -m pip install --upgrade pip
           mkdir -p ${GITHUB_WORKSPACE}/cli-beta
           pip install --target ${GITHUB_WORKSPACE}/cli-beta --extra-index-url https://azurecliedge.blob.core.windows.net/federated-token/simple/ azure-cli
           cp ~/.bashrc ~/.bashrc.bak
           echo "export PATH=${GITHUB_WORKSPACE}/cli-beta/bin:$PATH" >> .bashrc
           source ~/.bashrc
           pip install -r pythonSample_thecatsaidno/requirements.txt
           
      - name: 'Az CLI login without subscription'
        uses: 'balaga-gayatri/login@oidc-support'
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_OIDC }}
#           allow-no-subscriptions: true
#           enable-AzPSSession: true
          
      - name: 'Run az commands'
        run: |
          pwd
          which az
          az account show
          az group list
          pwd
          cd
          cat .zshrc
          
          
      - name: 'Deploy using webapps-deploy'
        uses: Azure/webapps-deploy@v2
        with: 
           app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
           package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
      - name: 'restore original .bashrc'
        run: |
            mv ~/.bashrc.bak ~/.bashrc
            source ~/.bashrc
