name: Run Azure Login with OIDC(testing)
on: workflow_dispatch
# D:\a\azure-login-action-tests\azure-login-action-tests\
#            py -3.10 -m venv oidc-venv

permissions:
      id-token: write
      contents: write
jobs: 
  az-login-test:
    runs-on: ubuntu-latest
    steps:
      - name: Installing CLI-beta for OIDC
        run: |
           cd /home/runner/work
           CWD="$(pwd)" 
           python3 -m venv oidc-venv
           . oidc-venv/bin/activate
           echo "activated environment" 
           python3 -m pip install -q --upgrade pip
           echo "started installing cli beta" 
           pip install -q --extra-index-url https://azurecliedge.blob.core.windows.net/federated-token/simple/ azure-cli
           echo "***************installed cli beta*******************" 
           echo "$CWD/oidc-venv/bin" >> $GITHUB_PATH
           ls
           
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: testing files-1
        run: |
          which az
          echo $PATH
          cd /home/runner/work
          ls
          
      - name: 'Az CLI login'
        uses: 'azure/login@oidc-support'
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}     

      - name: Check out repository
        uses: actions/checkout@v2
  
      - name: testing files-2
        run: |
            which az
            ls
              
      - run: |
          az account show
          az group list
          pwd 
    
#${{ secrets.AZURE_CLIENTID }}
#   . .\oidc-venv\Scripts\Activate.ps1
#            echo "activated environment" 
#            python3 -m pip install -q --upgrade pip
#            echo "started installing cli beta" 
#            pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
#            echo "***************installed cli beta*******************"         
#            echo "$CWD\oidc-venv\bin" >> $GITHUB_PATH

#  - uses: actions/setup-python@v2
#         with:
#            python-version: '3.x'
           
#       - run: |
#            $CWD = Convert-Path .
#            echo $CWD
#            python --version
#            python -m venv oidc-venv
#            . .\oidc-venv\Scripts\Activate.ps1
#            python -m pip install -q --upgrade pip
#            echo "started installing cli beta" 
#            pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
#            echo "***************installed cli beta*******************" 
#            echo "echo path"
#            echo "$env:Path"
#            echo "$env:GITHUB_PATH"
#            echo "$CWD\oidc-venv\Scripts" >> $env:GITHUB_PATH
#            echo "$env:GITHUB_PATH"
#            echo $env:PATH
