name: Run Azure Login for OIDC
on: workflow_dispatch

permissions:
      id-token: write
      contents: write
jobs: 
  az-login-test:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Installing CLI-beta for OIDC
        run: |
           pwd 
           python3 -m venv oidc-venv
           ls
           . oidc-venv/bin/activate
           python3 -m pip install --upgrade pip
           pip install --extra-index-url https://azurecliedge.blob.core.windows.net/federated-token/simple/ azure-cli
           
      - name: 'Az CLI login without subscription'
        uses: 'balaga-gayatri/login@oidc-support'
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_OIDC }}
#           allow-no-subscriptions: true
#           enable-AzPSSession: true
          
      - run: |
          pwd
          . ~/oidc-venv/bin/activate
          az account show
          az group list
          pwd 
#       - name: deactive and remove cli beta venv
#         run: |
#           deactivate
#           rm -rf oidc-venv
#           . /Users/balaga-gayatri/actions-runner/_work/azure-login-action-tests/azure-login-action-tests/oidc-venv/bin/activate
