name: Run  azlogin checks for all cases
on: workflow_dispatch
env:
 ACTION-NAME: 'azure/login@oidc-support'
jobs:
  Windows-latest:
      runs-on: windows-latest
      steps:

        # windows CLI installation 
        - name: Install CLI-beta
          run: |
              cd ../..
              $CWD = Convert-Path .
              echo $CWD
              python --version
              python -m venv oidc-venv
              . .\oidc-venv\Scripts\Activate.ps1
              python -m pip install -q --upgrade pip
              echo "started installing cli beta" 
              pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
              echo "installed cli beta" 
              echo "$CWD\oidc-venv\Scripts" >> $env:GITHUB_PATH

        - name: Installing preview Az.accounts for powershell
          shell: pwsh
          run: |
            cd ../../oidc-venv
            Invoke-WebRequest -Uri https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.6.0.nupkg -outfile "Az.Accounts.2.6.0.nupkg"
            Register-PSRepository -Name LocalPSRepo -SourceLocation "$(pwd)" -ScriptSourceLocation "$(pwd)" -InstallationPolicy Trusted
            Install-Module Az.Accounts -Repository LocalPSRepo

        - uses: actions/checkout@v2

        - name: OIDC Login to Azure Public Cloud with CLI (no enableAzPSSession )
          uses: ${{env.ACTION-NAME}}
          with:
            client-id: ${{ secrets.AZURE_CLIENTID }}
            tenant-id: ${{ secrets.AZURE_TENANTID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }} 
        - run: |
              az account show      
        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: 'azure/login@oidc-support'
          with:
            client-id: ${{ secrets.AZURE_CLIENTID }}
            tenant-id: ${{ secrets.AZURE_TENANTID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }} 
            enable-AzPSSession: true

        - name: 'Get RG with powershell action'
          uses: azure/powershell@v1
          with:
             inlineScript: |
               Get-AzResourceGroup
               azPSVersion: "latest"
        - run: |
              az account show
              az logout

        - name: non-OIDC Login to Azure Public Cloud with CLI (no enableAzPSSession )
          uses: azure/login@oidc-support
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}      
        - run: |
              az account show 

        - name: non-OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: azure/login@oidc-support
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            enable-AzPSSession: true

        - name: 'Get RG with powershell action'
          uses: azure/powershell@v1
          with:
             inlineScript: |
               Get-AzResourceGroup
               azPSVersion: "latest"
        - run: |
              az account show
              az logout

        - name: non-OIDC login to Azure China  Cloud with CLI ( evironment variable set to  AzureChinaCloud)
          uses: azure/login@oidc-support
          with:
            creds: ${{ secrets.AZURE_CHINA_GOV_CLOUD_CREDENTIALS }}
            environment: 'AzureChinaCloud'
        - run: |
              az account show  

        - name: non-OIDC login to Azure China  Cloud with Az Powershell (  evironment variable set to  AzureChinaCloud  and  enableAzPSSession true)
          uses: azure/login@oidc-support
          with:
            creds: ${{ secrets.AZURE_CHINA_GOV_CLOUD_CREDENTIALS }}
            environment: 'AzureChinaCloud'
            enable-AzPSSession: true

        - name: 'Get RG with powershell action'
          uses: azure/powershell@v1
          with:
             inlineScript: |
               Get-AzResourceGroup
               azPSVersion: "latest"
        - run: |
              az account show
              az logout

  Ubuntu-latest:
      runs-on: ubuntu-latest
      steps:

        # ubuntu CLI installation 
        - name: Install CLI-beta
          run: |
             cd ../..
             CWD="$(pwd)"
             python3 -m venv oidc-venv
             . oidc-venv/bin/activate
             echo "activated environment" 
             python3 -m pip install --upgrade pip
             echo "started installing cli beta" 
             pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
             echo "installed cli beta"    
             echo "$CWD/oidc-venv/bin" >> $GITHUB_PATH   

        - name: Installing preview Az.accounts for powershell
          shell: pwsh
          run: |
            cd ../../oidc-venv
            Invoke-WebRequest -Uri https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.6.0.nupkg -outfile "Az.Accounts.2.6.0.nupkg"
            Register-PSRepository -Name LocalPSRepo -SourceLocation "$(pwd)" -ScriptSourceLocation "$(pwd)" -InstallationPolicy Trusted
            Install-Module Az.Accounts -Repository LocalPSRepo

        - uses: actions/checkout@v2

        - name: OIDC Login to Azure Public Cloud with CLI (no enableAzPSSession )
          uses: 'azure/login@oidc-support'
          with:
            client-id: ${{ secrets.AZURE_CLIENTID }}
            tenant-id: ${{ secrets.AZURE_TENANTID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }} 
        - run: |
             az account show      
        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: 'azure/login@oidc-support'
          with:
            client-id: ${{ secrets.AZURE_CLIENTID }}
            tenant-id: ${{ secrets.AZURE_TENANTID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }} 
            enable-AzPSSession: true

        - name: 'Get RG with powershell action'
          uses: azure/powershell@v1
          with:
             inlineScript: |
               Get-AzResourceGroup
               azPSVersion: "latest"
        - run: |
              az account show
              az logout

        - name: non-OIDC Login to Azure Public Cloud with CLI (no enableAzPSSession )
          uses: azure/login@oidc-support
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}      
        - run: |
              az account show 

        - name: non-OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: azure/login@oidc-support
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            enable-AzPSSession: true

        - name: 'Get RG with powershell action'
          uses: azure/powershell@v1
          with:
             inlineScript: |
               Get-AzResourceGroup
               azPSVersion: "latest"
        - run: |
              az account show
              az logout

        - name: non-OIDC login to Azure China  Cloud with CLI ( evironment variable set to  AzureChinaCloud)
          uses: azure/login@oidc-support
          with:
            creds: ${{ secrets.AZURE_CHINA_GOV_CLOUD_CREDENTIALS }}
            environment: 'AzureChinaCloud'
        - run: |
              az account show  

        - name: non-OIDC login to Azure China  Cloud with Az Powershell (  evironment variable set to  AzureChinaCloud  and  enableAzPSSession true)
          uses: azure/login@oidc-support
          with:
            creds: ${{ secrets.AZURE_CHINA_GOV_CLOUD_CREDENTIALS }}
            environment: 'AzureChinaCloud'
            enable-AzPSSession: true

        - name: 'Get RG with powershell action'
          uses: azure/powershell@v1
          with:
             inlineScript: |
               Get-AzResourceGroup
               azPSVersion: "latest"
        - run: |
              az account show
              az logout


  macos-latest:
    runs-on: macos-latest
    steps:

      # ubuntu CLI installation 
      - name: Install CLI-beta
        run: |
           cd ../..
           CWD="$(pwd)"
           python3 -m venv oidc-venv
           . oidc-venv/bin/activate
           echo "activated environment" 
           python3 -m pip install --upgrade pip
           echo "started installing cli beta" 
           pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
           echo "installed cli beta"    
           echo "$CWD/oidc-venv/bin" >> $GITHUB_PATH   

      - name: Installing preview Az.accounts for powershell
        shell: pwsh
        run: |
          cd ../../oidc-venv
          Invoke-WebRequest -Uri https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.6.0.nupkg -outfile "Az.Accounts.2.6.0.nupkg"
          Register-PSRepository -Name LocalPSRepo -SourceLocation "$(pwd)" -ScriptSourceLocation "$(pwd)" -InstallationPolicy Trusted
          Install-Module Az.Accounts -Repository LocalPSRepo

      - uses: actions/checkout@v2

      - name: OIDC Login to Azure Public Cloud with CLI (no enableAzPSSession )
        uses: 'azure/login@oidc-support'
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }} 

      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: 'azure/login@oidc-support'
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }} 
          enable-AzPSSession: true

      - name: 'Get RG with powershell action'
        uses: azure/powershell@v1
        with:
           inlineScript: |
             Get-AzResourceGroup
             azPSVersion: "latest"
      - run: |
              az account show
              az logout

      - name: non-OIDC Login to Azure Public Cloud with CLI (no enableAzPSSession )
        uses: azure/login@oidc-support
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}      
      - run: |
            az account show 

      - name: non-OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@oidc-support
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: 'Get RG with powershell action'
        uses: azure/powershell@v1
        with:
           inlineScript: |
             Get-AzResourceGroup
             azPSVersion: "latest"
      - run: |
            az account show    
            az logout


      - name: non-OIDC login to Azure China  Cloud with CLI ( evironment variable set to  AzureChinaCloud)
        uses: azure/login@oidc-support
        with:
          creds: ${{ secrets.AZURE_CHINA_GOV_CLOUD_CREDENTIALS }}
          environment: 'AzureChinaCloud'
      - run: |
            az account show  

      - name: non-OIDC login to Azure China  Cloud with Az Powershell (  evironment variable set to  AzureChinaCloud  and  enableAzPSSession true)
        uses: azure/login@oidc-support
        with:
          creds: ${{ secrets.AZURE_CHINA_GOV_CLOUD_CREDENTIALS }}
          environment: 'AzureChinaCloud'
          enable-AzPSSession: true

      - name: 'Get RG with powershell action'
        uses: azure/powershell@v1
        with:
           inlineScript: |
             Get-AzResourceGroup
             azPSVersion: "latest"

      - run: |
           az account show  


