name: Run Azure Login  PS
on: workflow_dispatch

permissions:
      id-token: write
      contents: write
jobs: 
  az-login-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
  
      - name: Set Parameter
        id: tasksetparameter
        uses: azure/powershell@v1
        with:
            inlineScript: |
                   $PARAM = "test"
                   echo $PARAM
                   echo ::set-output name=myparam::$PARAM
            azPSVersion: latest

      - name: Read Parameter
#         uses: azure/powershell@v1
#         with:
#            inlineScript: |
        shell: bash
        run: |
                  echo "${{ steps.tasksetparameter.outputs.myparam }}"
           
#    azPSVersion: latest
