name: Run Azure Login  PS
on: workflow_dispatch

permissions:
      id-token: write
      contents: write
jobs: 
  az-login-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
  
      - name: Set Parameter
        id: tasksetparameter
#         uses: azure/powershell@v1
#         with:
#             inlineScript: |
        shell: pwsh
        run: |
                  Write-Output ::set-output name=myparam::"test"

      - name: Read Parameter
#         uses: azure/powershell@v1
#         with:
#            inlineScript: |
        shell: pwsh
        run: |
             Write-Output '${{ steps.tasksetparameter.outputs.myparam }}'
        
