name: Run Azure Login  PS
on: workflow_dispatch

permissions:
      id-token: write
      contents: write
jobs: 
  az-login-test:
    runs-on: ubuntu-latest
    steps:
#       - name: Check out repository
#         uses: actions/checkout@v2
      - uses: actions/checkout@v1
      - name: Set outputs
        id: vars
        shell: pwsh
        run: echo "::set-output name=production::true"
      - name: Check outputs
        shell: pwsh
        run: echo ${{ steps.vars.outputs.production }}
  
      - name: Set Parameter
        id: tasksetparameter
        uses: azure/powershell@v1
        with:
            inlineScript: |
                  $param = ("test")
                  echo ::set-output name=myparam::$( $param)
            azPSVersion: latest

      - name: Read Parameter
        uses: azure/powershell@v1
        with:
           inlineScript: |
             echo "${{ steps.tasksetparameter.outputs.myparam }}" 
           azPSVersion: latest
#         shell: bash
#         run: |
             
           
#    azPSVersion: latest
