# sql-deploy.yml
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    #CLI Dependency Testing - START
    
    - name: Installing CLI-beta for OIDC 
      run: |
         CWD="$(pwd)"  
         python3 -m venv oidc-venv
         . oidc-venv/bin/activate
         echo "activated environment" 
         python3 -m pip install -q --upgrade pip
         echo "started installing cli beta" 
         pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli 
         echo "***************installed cli beta*******************" 
         echo "$CWD/oidc-venv/bin" >> $GITHUB_PATH

    
    #CLI Dependency Testing - END
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTAILS }}
    - uses: azure/sql-action@v1
      with:
        server-name: 'mysqlserver-ak.database.windows.net'
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        sql-file: './sql_action.sql'
